import { Meal } from "./types";

export const mealTemplates: Meal[] = [
  {
    id: "keto-yogurt",
    name: "Yogurt greco, noci e semi",
    mealType: "breakfast",
    dietTypes: ["ketogenic", "lowCarb", "balanced"],
    ingredients: [
      { name: "Yogurt greco intero", grams: 170 },
      { name: "Noci", grams: 25 },
      { name: "Semi di chia", grams: 10 },
    ],
    calories: 360,
    protein: 22,
    carbs: 12,
    fats: 25,
    tags: ["zeroSbatti", "low carb"],
  },
  {
    id: "med-porridge",
    name: "Porridge mediterraneo con frutta",
    mealType: "breakfast",
    dietTypes: ["mediterranean", "balanced", "vegetarian"],
    ingredients: [
      { name: "Fiocchi d'avena", grams: 55 },
      { name: "Latte parzialmente scremato", grams: 180 },
      { name: "Mela", grams: 120 },
      { name: "Mandorle", grams: 12 },
    ],
    calories: 430,
    protein: 18,
    carbs: 62,
    fats: 13,
    tags: ["budget", "saziante"],
  },
  {
    id: "veg-toast",
    name: "Toast integrale con uova e spinaci",
    mealType: "breakfast",
    dietTypes: ["mediterranean", "balanced", "vegetarian"],
    ingredients: [
      { name: "Pane integrale", grams: 70 },
      { name: "Uova", grams: 110 },
      { name: "Spinaci", grams: 80 },
    ],
    calories: 410,
    protein: 25,
    carbs: 38,
    fats: 17,
    tags: ["semplice", "proteico"],
  },
  {
    id: "keto-eggs",
    name: "Omelette con zucchine e feta",
    mealType: "breakfast",
    dietTypes: ["ketogenic", "lowCarb", "vegetarian"],
    ingredients: [
      { name: "Uova", grams: 150 },
      { name: "Zucchine", grams: 120 },
      { name: "Feta", grams: 45 },
      { name: "Olio extravergine", grams: 8 },
    ],
    calories: 470,
    protein: 31,
    carbs: 9,
    fats: 35,
    tags: ["keto", "meal prep"],
  },
  {
    id: "med-chicken-bowl",
    name: "Bowl pollo, farro e verdure",
    mealType: "lunch",
    dietTypes: ["mediterranean", "balanced"],
    ingredients: [
      { name: "Petto di pollo", grams: 150 },
      { name: "Farro cotto", grams: 150 },
      { name: "Pomodori", grams: 120 },
      { name: "Cetrioli", grams: 100 },
      { name: "Olio extravergine", grams: 10 },
    ],
    calories: 610,
    protein: 48,
    carbs: 58,
    fats: 18,
    tags: ["meal prep", "saziante"],
  },
  {
    id: "keto-salmon-salad",
    name: "Insalata salmone e avocado",
    mealType: "lunch",
    dietTypes: ["ketogenic", "lowCarb"],
    ingredients: [
      { name: "Salmone", grams: 150 },
      { name: "Avocado", grams: 90 },
      { name: "Insalata mista", grams: 120 },
      { name: "Olio extravergine", grams: 10 },
    ],
    calories: 650,
    protein: 36,
    carbs: 10,
    fats: 51,
    tags: ["zeroSbatti", "keto"],
  },
  {
    id: "veg-lentil-bowl",
    name: "Bowl lenticchie, riso e yogurt",
    mealType: "lunch",
    dietTypes: ["mediterranean", "balanced", "vegetarian"],
    ingredients: [
      { name: "Lenticchie cotte", grams: 180 },
      { name: "Riso integrale cotto", grams: 120 },
      { name: "Yogurt greco", grams: 90 },
      { name: "Carote", grams: 100 },
    ],
    calories: 590,
    protein: 32,
    carbs: 86,
    fats: 10,
    tags: ["budget", "vegetariano"],
  },
  {
    id: "low-carb-turkey",
    name: "Tacchino con cavolfiore e olive",
    mealType: "lunch",
    dietTypes: ["lowCarb", "balanced"],
    ingredients: [
      { name: "Fesa di tacchino", grams: 160 },
      { name: "Cavolfiore", grams: 220 },
      { name: "Olive", grams: 35 },
      { name: "Olio extravergine", grams: 10 },
    ],
    calories: 500,
    protein: 47,
    carbs: 18,
    fats: 25,
    tags: ["low carb", "budget"],
  },
  {
    id: "balanced-tuna-pasta",
    name: "Pasta integrale tonno e pomodoro",
    mealType: "lunch",
    dietTypes: ["mediterranean", "balanced"],
    ingredients: [
      { name: "Pasta integrale", grams: 80 },
      { name: "Tonno al naturale", grams: 120 },
      { name: "Passata di pomodoro", grams: 140 },
      { name: "Olio extravergine", grams: 8 },
    ],
    calories: 560,
    protein: 42,
    carbs: 66,
    fats: 13,
    tags: ["semplice", "budget"],
  },
  {
    id: "med-sea-bass",
    name: "Orata con patate e verdure",
    mealType: "dinner",
    dietTypes: ["mediterranean", "balanced"],
    ingredients: [
      { name: "Orata", grams: 170 },
      { name: "Patate", grams: 180 },
      { name: "Fagiolini", grams: 160 },
      { name: "Olio extravergine", grams: 10 },
    ],
    calories: 560,
    protein: 42,
    carbs: 45,
    fats: 20,
    tags: ["mediterraneo", "saziante"],
  },
  {
    id: "keto-beef-broccoli",
    name: "Manzo, broccoli e crema di ricotta",
    mealType: "dinner",
    dietTypes: ["ketogenic", "lowCarb"],
    ingredients: [
      { name: "Manzo magro", grams: 150 },
      { name: "Broccoli", grams: 220 },
      { name: "Ricotta", grams: 70 },
      { name: "Olio extravergine", grams: 8 },
    ],
    calories: 620,
    protein: 48,
    carbs: 16,
    fats: 39,
    tags: ["proteico", "low carb"],
  },
  {
    id: "veg-tofu-stir",
    name: "Tofu saltato con verdure e quinoa",
    mealType: "dinner",
    dietTypes: ["vegetarian", "balanced", "mediterranean"],
    ingredients: [
      { name: "Tofu", grams: 170 },
      { name: "Quinoa cotta", grams: 130 },
      { name: "Peperoni", grams: 120 },
      { name: "Zucchine", grams: 120 },
      { name: "Olio extravergine", grams: 8 },
    ],
    calories: 580,
    protein: 32,
    carbs: 52,
    fats: 25,
    tags: ["vegetariano", "meal prep"],
  },
  {
    id: "balanced-turkey-burger",
    name: "Burger di tacchino con insalata e pane",
    mealType: "dinner",
    dietTypes: ["balanced", "mediterranean"],
    ingredients: [
      { name: "Burger di tacchino", grams: 160 },
      { name: "Pane integrale", grams: 65 },
      { name: "Insalata mista", grams: 130 },
      { name: "Pomodori", grams: 100 },
    ],
    calories: 540,
    protein: 43,
    carbs: 45,
    fats: 18,
    tags: ["semplice", "famiglia"],
  },
  {
    id: "snack-skyr",
    name: "Skyr e frutti rossi",
    mealType: "snack",
    dietTypes: ["mediterranean", "balanced", "lowCarb", "vegetarian"],
    ingredients: [
      { name: "Skyr", grams: 170 },
      { name: "Frutti rossi", grams: 90 },
    ],
    calories: 170,
    protein: 19,
    carbs: 20,
    fats: 1,
    tags: ["zeroSbatti", "anti-fame"],
  },
  {
    id: "snack-hummus",
    name: "Hummus e carote",
    mealType: "snack",
    dietTypes: ["mediterranean", "balanced", "vegetarian"],
    ingredients: [
      { name: "Hummus", grams: 70 },
      { name: "Carote", grams: 130 },
    ],
    calories: 210,
    protein: 7,
    carbs: 22,
    fats: 10,
    tags: ["budget", "vegetariano"],
  },
  {
    id: "snack-keto-cheese",
    name: "Parmigiano e cetrioli",
    mealType: "snack",
    dietTypes: ["ketogenic", "lowCarb", "vegetarian"],
    ingredients: [
      { name: "Parmigiano", grams: 35 },
      { name: "Cetrioli", grams: 160 },
    ],
    calories: 180,
    protein: 13,
    carbs: 6,
    fats: 11,
    tags: ["keto", "zeroSbatti"],
  },
];
