export type BacklogPriority = "P0" | "P1" | "P2" | "P3";
export type BacklogStatus = "done" | "next" | "planned" | "later";

export type BacklogItem = {
  id: string;
  title: string;
  detail: string;
  area: string;
  priority: BacklogPriority;
  status: BacklogStatus;
};

export const backlogAreas = [
  "Fondamenta",
  "Account",
  "Privacy",
  "Planner",
  "Nutrizione",
  "Piani",
  "Spesa",
  "AI coach",
  "Premium",
  "Admin",
  "Qualita",
  "Growth",
  "Mobile",
] as const;

export const backlogItems: BacklogItem[] = [
  {
    id: "foundation-domain",
    title: "Dominio e deploy automatico",
    detail: "dietsprintai.com collegato a Vercel con deploy da main.",
    area: "Fondamenta",
    priority: "P0",
    status: "done",
  },
  {
    id: "foundation-supabase",
    title: "Database Supabase con RLS",
    detail: "Schema MVP, migrazione iniziale e policy per dati proprietari.",
    area: "Fondamenta",
    priority: "P0",
    status: "done",
  },
  {
    id: "foundation-resend",
    title: "Email Resend e SMTP Auth",
    detail: "Invio applicativo e messaggi Supabase Auth dal dominio verificato.",
    area: "Fondamenta",
    priority: "P0",
    status: "done",
  },
  {
    id: "foundation-preview",
    title: "Ambiente Preview separato",
    detail: "Variabili e database staging per validare branch prima della produzione.",
    area: "Fondamenta",
    priority: "P1",
    status: "planned",
  },
  {
    id: "foundation-backups",
    title: "Backup e ripristino database",
    detail: "Strategia backup, retention e prova periodica di restore.",
    area: "Fondamenta",
    priority: "P0",
    status: "next",
  },
  {
    id: "account-email-password",
    title: "Registrazione email e password",
    detail: "Creazione account, conferma email, login e logout.",
    area: "Account",
    priority: "P0",
    status: "done",
  },
  {
    id: "account-reset",
    title: "Recupero e cambio password",
    detail: "Reset via email e aggiornamento credenziali dall'account.",
    area: "Account",
    priority: "P0",
    status: "next",
  },
  {
    id: "account-profile-edit",
    title: "Modifica profilo alimentare",
    detail: "Aggiornare dati, preferenze, esclusioni e obiettivi salvati.",
    area: "Account",
    priority: "P1",
    status: "next",
  },
  {
    id: "account-onboarding",
    title: "Onboarding guidato",
    detail: "Percorso iniziale progressivo con salvataggio bozza e ripresa.",
    area: "Account",
    priority: "P1",
    status: "planned",
  },
  {
    id: "account-security-alerts",
    title: "Notifiche sicurezza account",
    detail: "Email per password modificata, cambio email e accessi sospetti.",
    area: "Account",
    priority: "P1",
    status: "planned",
  },
  {
    id: "account-delete",
    title: "Eliminazione account self-service",
    detail: "Conferma rafforzata, cancellazione dati e ricevuta email.",
    area: "Account",
    priority: "P1",
    status: "planned",
  },
  {
    id: "account-family",
    title: "Profili famiglia",
    detail: "Gestire più persone, preferenze e piani dallo stesso abbonamento.",
    area: "Account",
    priority: "P3",
    status: "later",
  },
  {
    id: "privacy-pages",
    title: "Pagine legali MVP",
    detail: "Privacy, termini, cookie, GDPR e disclaimer salute.",
    area: "Privacy",
    priority: "P0",
    status: "done",
  },
  {
    id: "privacy-review",
    title: "Revisione legale professionale",
    detail: "Validare testi, titolare, basi giuridiche, fornitori e retention.",
    area: "Privacy",
    priority: "P0",
    status: "next",
  },
  {
    id: "privacy-consent-versioning",
    title: "Versionamento consensi",
    detail: "Storico consensi per versione documento e timestamp.",
    area: "Privacy",
    priority: "P1",
    status: "planned",
  },
  {
    id: "privacy-cookie-banner",
    title: "Cookie banner reale",
    detail: "Consenso granulare prima di analytics o strumenti non essenziali.",
    area: "Privacy",
    priority: "P1",
    status: "planned",
  },
  {
    id: "privacy-export",
    title: "Export dati utente",
    detail: "Generare un archivio leggibile con profilo, piani e consensi.",
    area: "Privacy",
    priority: "P1",
    status: "planned",
  },
  {
    id: "privacy-request-workflow",
    title: "Workflow richieste GDPR",
    detail: "Stati, assegnazione, scadenze, note interne e chiusura richiesta.",
    area: "Privacy",
    priority: "P1",
    status: "planned",
  },
  {
    id: "planner-core",
    title: "Planner guidato MVP",
    detail: "Dati personali, attività, obiettivo, dieta, pasti, budget e semplicità.",
    area: "Planner",
    priority: "P0",
    status: "done",
  },
  {
    id: "planner-save-draft",
    title: "Salvataggio bozza planner",
    detail: "Riprendere la compilazione su altro dispositivo o in seguito.",
    area: "Planner",
    priority: "P1",
    status: "planned",
  },
  {
    id: "planner-medical-screening",
    title: "Screening prudenziale iniziale",
    detail: "Avvisi per gravidanza, patologie, farmaci, diabete e disturbi alimentari.",
    area: "Planner",
    priority: "P0",
    status: "next",
  },
  {
    id: "planner-allergies",
    title: "Allergie e intolleranze strutturate",
    detail: "Selezioni dedicate separate dalle semplici preferenze.",
    area: "Planner",
    priority: "P1",
    status: "planned",
  },
  {
    id: "planner-time",
    title: "Tempo disponibile per cucinare",
    detail: "Preferenze per pasti pronti, rapidi, batch cooking o cucina completa.",
    area: "Planner",
    priority: "P1",
    status: "planned",
  },
  {
    id: "planner-pantry",
    title: "Dispensa disponibile",
    detail: "Riutilizzare ingredienti già presenti per ridurre costi e sprechi.",
    area: "Planner",
    priority: "P2",
    status: "later",
  },
  {
    id: "nutrition-bmr",
    title: "Calcolo BMR e TDEE",
    detail: "Formula Mifflin-St Jeor, attività e calorie suggerite.",
    area: "Nutrizione",
    priority: "P0",
    status: "done",
  },
  {
    id: "nutrition-safety",
    title: "Guardrail calorie basse",
    detail: "Blocchi e avvisi chiari per target restrittivi o non appropriati.",
    area: "Nutrizione",
    priority: "P0",
    status: "done",
  },
  {
    id: "nutrition-macros",
    title: "Macro coerenti per dieta",
    detail: "Range indicativi per proteine, carboidrati e grassi per stile alimentare.",
    area: "Nutrizione",
    priority: "P1",
    status: "planned",
  },
  {
    id: "nutrition-fiber",
    title: "Indicatori fibre e idratazione",
    detail: "Suggerimenti pratici non medicali per equilibrio e sazietà.",
    area: "Nutrizione",
    priority: "P2",
    status: "later",
  },
  {
    id: "nutrition-validation",
    title: "Revisione nutrizionista",
    detail: "Validare logica, template e guardrail prima della beta pubblica.",
    area: "Nutrizione",
    priority: "P0",
    status: "next",
  },
  {
    id: "plans-daily-weekly",
    title: "Piano giornaliero e settimanale",
    detail: "Generazione deterministica con ingredienti, quantità e macro.",
    area: "Piani",
    priority: "P0",
    status: "done",
  },
  {
    id: "plans-history",
    title: "Storico piani salvati",
    detail: "Aprire, duplicare, archiviare ed eliminare i piani precedenti.",
    area: "Piani",
    priority: "P1",
    status: "next",
  },
  {
    id: "plans-detail",
    title: "Dettaglio piano salvato",
    detail: "Vista completa con giorni, pasti, ingredienti e note.",
    area: "Piani",
    priority: "P1",
    status: "next",
  },
  {
    id: "plans-regenerate-meal",
    title: "Rigenera singolo pasto",
    detail: "Sostituire una proposta mantenendo dieta, calorie e semplicità.",
    area: "Piani",
    priority: "P1",
    status: "planned",
  },
  {
    id: "plans-substitutions",
    title: "Sostituzioni compatibili",
    detail: "Alternative equivalenti per gusto, reperibilità e costo.",
    area: "Piani",
    priority: "P1",
    status: "planned",
  },
  {
    id: "plans-favorites",
    title: "Pasti preferiti",
    detail: "Salvare ricette gradite e aumentare la loro frequenza.",
    area: "Piani",
    priority: "P2",
    status: "later",
  },
  {
    id: "plans-feedback",
    title: "Feedback rapido sui pasti",
    detail: "Mi piace, non mi piace, troppo complesso, troppo costoso.",
    area: "Piani",
    priority: "P2",
    status: "later",
  },
  {
    id: "plans-pdf",
    title: "Export PDF",
    detail: "Piano e lista spesa stampabili con layout mobile e desktop.",
    area: "Piani",
    priority: "P2",
    status: "planned",
  },
  {
    id: "grocery-basic",
    title: "Lista spesa aggregata",
    detail: "Ingredienti raggruppati dal piano settimanale.",
    area: "Spesa",
    priority: "P0",
    status: "done",
  },
  {
    id: "grocery-categories",
    title: "Categorie supermercato",
    detail: "Ortofrutta, dispensa, freschi, surgelati e quantità consolidate.",
    area: "Spesa",
    priority: "P1",
    status: "planned",
  },
  {
    id: "grocery-checklist",
    title: "Checklist spesa interattiva",
    detail: "Spuntare prodotti e mantenere stato per piano.",
    area: "Spesa",
    priority: "P1",
    status: "planned",
  },
  {
    id: "grocery-budget",
    title: "Budget stimato",
    detail: "Stima costi e sostituzioni economiche per ingredienti costosi.",
    area: "Spesa",
    priority: "P2",
    status: "later",
  },
  {
    id: "grocery-meal-prep",
    title: "Meal prep settimanale",
    detail: "Sessioni di preparazione, conservazione e riuso intelligente.",
    area: "Spesa",
    priority: "P2",
    status: "later",
  },
  {
    id: "ai-server",
    title: "Layer AI server-side",
    detail: "Prompt protetti, provider configurabile e nessuna chiave nel browser.",
    area: "AI coach",
    priority: "P1",
    status: "planned",
  },
  {
    id: "ai-guardrails",
    title: "Guardrail AI salute",
    detail: "Regole deterministiche prima e dopo ogni risposta generata.",
    area: "AI coach",
    priority: "P0",
    status: "planned",
  },
  {
    id: "ai-anti-hunger",
    title: "Coach anti-fame",
    detail: "Suggerimenti pratici, non medicali e contestuali per aderenza e voglie.",
    area: "AI coach",
    priority: "P2",
    status: "later",
  },
  {
    id: "ai-chat",
    title: "Chat coach contestuale",
    detail: "Domande sul piano attivo, sostituzioni e organizzazione quotidiana.",
    area: "AI coach",
    priority: "P3",
    status: "later",
  },
  {
    id: "ai-learning",
    title: "Personalizzazione progressiva",
    detail: "Adattare proposte in base a feedback, preferiti e rigenerazioni.",
    area: "AI coach",
    priority: "P3",
    status: "later",
  },
  {
    id: "ai-evaluation",
    title: "Valutazione qualità output AI",
    detail: "Dataset di test, controlli regressione e revisione umana periodica.",
    area: "AI coach",
    priority: "P1",
    status: "planned",
  },
  {
    id: "premium-plans",
    title: "Piani Free, Premium e Pro",
    detail: "Feature gate, limiti e benefici chiari per ciascun livello.",
    area: "Premium",
    priority: "P1",
    status: "planned",
  },
  {
    id: "premium-stripe",
    title: "Checkout Stripe",
    detail: "Acquisto abbonamento, webhook e aggiornamento stato utente.",
    area: "Premium",
    priority: "P1",
    status: "planned",
  },
  {
    id: "premium-portal",
    title: "Portale cliente",
    detail: "Gestire carta, fatture, upgrade, downgrade e cancellazione.",
    area: "Premium",
    priority: "P1",
    status: "planned",
  },
  {
    id: "premium-trial",
    title: "Trial e coupon",
    detail: "Prove controllate, codici promozionali e campagne lancio.",
    area: "Premium",
    priority: "P2",
    status: "later",
  },
  {
    id: "premium-invoices",
    title: "Fatturazione e ricevute",
    detail: "Email transazionali, storico pagamenti e dati fiscali.",
    area: "Premium",
    priority: "P2",
    status: "later",
  },
  {
    id: "admin-backlog",
    title: "Backlog admin protetto",
    detail: "Pannello operativo riservato già presente su /admin/backlog.",
    area: "Admin",
    priority: "P0",
    status: "done",
  },
  {
    id: "admin-users",
    title: "Gestione utenti",
    detail: "Ricerca, stato account, piano attivo e azioni di supporto.",
    area: "Admin",
    priority: "P1",
    status: "planned",
  },
  {
    id: "admin-gdpr",
    title: "Coda richieste privacy",
    detail: "Dashboard per lavorare richieste GDPR con audit trail.",
    area: "Admin",
    priority: "P1",
    status: "planned",
  },
  {
    id: "admin-content",
    title: "Gestione template pasti",
    detail: "CRUD ingredienti, ricette, tag dieta e sostituzioni.",
    area: "Admin",
    priority: "P1",
    status: "planned",
  },
  {
    id: "admin-metrics",
    title: "Metriche prodotto",
    detail: "Registrazioni, piani creati, conversione e retention.",
    area: "Admin",
    priority: "P2",
    status: "later",
  },
  {
    id: "admin-support",
    title: "Supporto utenti",
    detail: "Richieste, note interne, stato risoluzione e risposte email.",
    area: "Admin",
    priority: "P2",
    status: "later",
  },
  {
    id: "quality-e2e",
    title: "Test E2E flusso principale",
    detail: "Registrazione, conferma, login, planner, salvataggio e privacy.",
    area: "Qualita",
    priority: "P0",
    status: "next",
  },
  {
    id: "quality-calories-tests",
    title: "Test motore calorie",
    detail: "Copertura formule, soglie e casi limite.",
    area: "Qualita",
    priority: "P0",
    status: "next",
  },
  {
    id: "quality-error-tracking",
    title: "Monitoraggio errori",
    detail: "Error tracking frontend e server senza esporre dati sensibili.",
    area: "Qualita",
    priority: "P0",
    status: "next",
  },
  {
    id: "quality-accessibility",
    title: "Accessibilità base",
    detail: "Tastiera, focus, contrasto, label e screen reader.",
    area: "Qualita",
    priority: "P1",
    status: "planned",
  },
  {
    id: "quality-performance",
    title: "Performance mobile",
    detail: "Lighthouse, bundle, immagini e tempi di risposta.",
    area: "Qualita",
    priority: "P1",
    status: "planned",
  },
  {
    id: "quality-security",
    title: "Security review",
    detail: "Headers, rate limit, CAPTCHA, gestione segreti e dipendenze.",
    area: "Qualita",
    priority: "P1",
    status: "planned",
  },
  {
    id: "growth-analytics",
    title: "Analytics privacy-first",
    detail: "Eventi essenziali con consenso e funnel onboarding.",
    area: "Growth",
    priority: "P1",
    status: "planned",
  },
  {
    id: "growth-seo",
    title: "SEO tecnico",
    detail: "Metadata, sitemap, robots, Open Graph e pagine informative.",
    area: "Growth",
    priority: "P2",
    status: "later",
  },
  {
    id: "growth-newsletter",
    title: "Newsletter e onboarding email",
    detail: "Sequenze utili, consenso marketing separato e disiscrizione.",
    area: "Growth",
    priority: "P2",
    status: "later",
  },
  {
    id: "growth-referral",
    title: "Referral",
    detail: "Inviti, codici amico e misurazione conversioni.",
    area: "Growth",
    priority: "P3",
    status: "later",
  },
  {
    id: "growth-content",
    title: "Contenuti educativi",
    detail: "Guide pratiche su organizzazione, spesa e sostenibilità del piano.",
    area: "Growth",
    priority: "P3",
    status: "later",
  },
  {
    id: "mobile-pwa",
    title: "PWA installabile",
    detail: "Manifest, icone, comportamento mobile e accesso rapido.",
    area: "Mobile",
    priority: "P2",
    status: "later",
  },
  {
    id: "mobile-expo",
    title: "App Expo React Native",
    detail: "Client iOS e Android sugli stessi servizi backend.",
    area: "Mobile",
    priority: "P3",
    status: "later",
  },
  {
    id: "mobile-push",
    title: "Notifiche push",
    detail: "Promemoria piano, meal prep e spesa con preferenze granulari.",
    area: "Mobile",
    priority: "P3",
    status: "later",
  },
  {
    id: "mobile-offline",
    title: "Consultazione offline",
    detail: "Piano attivo e lista spesa disponibili anche senza rete.",
    area: "Mobile",
    priority: "P3",
    status: "later",
  },
];

export const backlogStatusLabels: Record<BacklogStatus, string> = {
  done: "Fatto",
  next: "Prossimo",
  planned: "Pianificato",
  later: "Più avanti",
};
